version: '3'

services:
  strong:
    image: strong:1
    ports:
      - "8080:8080"
    environment:
      - PROFILE=local
    network_mode: host
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yaml
    ports:
      - "9090:9090"