spring:
  profiles:
    active: ${PROFILE}
  main:
    allow-bean-definition-overriding: true

management:
  endpoint:
    health:
      show-details: always
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, prometheus
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    root: info
