spring:
  datasource:
    url: jdbc:postgresql://${PSQL_HOST}:${PSQL_PORT}/${PSQL_DB}
    username: ${PSQL_USER}
    password: ${PSQL_PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

logging:
  level:
    root: debug

protect:
  attempt:
    brute-force: 10
