spring:
  profiles:
    active: ${PROFILE}
  main:
    allow-bean-definition-overriding: true

management:
  endpoint:
    health:
      show-details: always
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, prometheus
  metrics:
    export:
      prometheus:
        enabled: true

springdoc:
  show-login-endpoint: true
  swagger-ui:
    disable-swagger-default-url: true

logging:
  level:
    root: info

web:
  cors:
    allowed-origins:
      - "http://localhost:8080"
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
    max-age: 86400
    allowed-headers:
      - "Origin"
      - "X-Api-Key"
      - "X-Requested-With"
      - "Content-Type"
      - "Accept"
      - "Authorization"
    exposed-headers:
      - "X-Get-Header"
